[package]
name = "spooks-wasm"
version = "0.1.1"
authors = ["Niklas Rosencrantz <niklasro@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
getopts = "0.2"
rand = {version = "0.7", features = ['stdweb']}
easy_reader = "0.5.0"
yew = { path = "../.." }
